package com.zzjz.bean;

import javax.xml.bind.annotation.XmlRootElement;

/**
 * 摄像头实体.
 *
 * @author fangguitang
 * @version 2017/11/17 16:40
 */
@XmlRootElement
public class Camera {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_camera.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_camera.camera_name
     *
     * @mbggenerated
     */
    private String cameraName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_camera.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_camera.only
     *
     * @mbggenerated
     */
    private String only;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_camera.ip
     *
     * @mbggenerated
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_camera.user_name
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_camera.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * 型号
     */
    private String model;

    /**
     * mac地址
     */
    private String mac;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_camera.id
     *
     * @return the value of tb_camera.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_camera.id
     *
     * @param id the value for tb_camera.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_camera.camera_name
     *
     * @return the value of tb_camera.camera_name
     *
     * @mbggenerated
     */
    public String getCameraName() {
        return cameraName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_camera.camera_name
     *
     * @param cameraName the value for tb_camera.camera_name
     *
     * @mbggenerated
     */
    public void setCameraName(String cameraName) {
        this.cameraName = cameraName == null ? null : cameraName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_camera.status
     *
     * @return the value of tb_camera.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_camera.status
     *
     * @param status the value for tb_camera.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_camera.only
     *
     * @return the value of tb_camera.only
     *
     * @mbggenerated
     */
    public String getOnly() {
        return only;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_camera.only
     *
     * @param only the value for tb_camera.only
     *
     * @mbggenerated
     */
    public void setOnly(String only) {
        this.only = only == null ? null : only.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_camera.ip
     *
     * @return the value of tb_camera.ip
     *
     * @mbggenerated
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_camera.ip
     *
     * @param ip the value for tb_camera.ip
     *
     * @mbggenerated
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_camera.user_name
     *
     * @return the value of tb_camera.user_name
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_camera.user_name
     *
     * @param userName the value for tb_camera.user_name
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_camera.password
     *
     * @return the value of tb_camera.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_camera.password
     *
     * @param password the value for tb_camera.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    public String getModel() {
        return model;
    }

    public void setModel(String model) {
        this.model = model;
    }

    public String getMac() {
        return mac;
    }

    public void setMac(String mac) {
        this.mac = mac;
    }
}
