package com.zzjz.mapper;

import com.zzjz.bean.Camera;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface CameraMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_camera
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_camera
     *
     * @mbggenerated
     */
    int insert(Camera record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_camera
     *
     * @mbggenerated
     */
    int insertSelective(Camera record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_camera
     *
     * @mbggenerated
     */
    Camera selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_camera
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Camera record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_camera
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Camera record);

    List<Camera> getCameraList(Camera camera);

    /**
     * 通过ip获取摄像头信息.
     * @param ip ip
     * @return 摄像头
     */
    Camera getCameraByIp(String ip);

    /**
     * 通过mac地址获取摄像头信息.
     * @param mac mac地址
     * @return 摄像头
     */
    Camera getCameraByMac(String mac);
}