package com.zzjz.mapper;

import com.zzjz.bean.Decoder;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface DecoderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_decoder
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_decoder
     *
     * @mbggenerated
     */
    int insertSelective(Decoder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_decoder
     *
     * @mbggenerated
     */
    Decoder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_decoder
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Decoder record);

    Decoder getDecoderInfoByIp(@Param("ip") String ip);

    List<Decoder> getDecoderList(Decoder decoder);

    /**
     * 根据mac地址获取解码器信息.
     * @param mac mac地址
     * @return 解码器
     */
    Decoder getDecoderInfoByMac(String mac);
}